### ISSUE TITLE
Implicit features due to target-specific optional dependencies are not added in current version

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#369]
> @obi1kenobi Upgrading to `v0.18` results in a failing semver check despite this crate not having received any significant changes. Could you look into this?

_Originally posted by @thomaseizinger in https://github.com/libp2p/rust-libp2p/issues/3469#issuecomment-1432218666_

Affected crate: `libp2p_uds` version `0.17`, repro commit `5b4eab7bafe6cba8fea6c806027ea680662b7cc6`

Its `Cargo.toml` contains the following block:
```toml
[target.'cfg(all(unix, not(target_os = "emscripten")))'.dependencies]
async-std = { version = "1.6.2", optional = true }
libp2p-core = { version = "0.38.0", path = "../../core" }
log = "0.4.1"
futures = "0.3.1"
tokio = { version = "1.15", default-features = false, features = ["net"], optional = true }
```

This implicitly defines features named `async-std` and `tokio`. These features are enabled in the baseline, but for some reason are not enabled in the "current":
```toml
[dependencies.libp2p-uds]
path = "/.../rust-libp2p/transports/uds"
features = []
default-features = false
```
