### ISSUE TITLE
invalid character `@` in pkgid (rust 1.58.1)

### ISSUE THREAD

**Issue by arnaudgolfouse** [obi1kenobi/cargo-semver-checks#444]
### Steps to reproduce the bug with the above code

```
git clone "https://gitlab.com/arnaudgolfouse/ielr.git"
cd ielr/
git reset --hard 834cfe85f0e5ddb78acf32c4f2d62c8ff6d110c4
cargo semver-checks check-release
```

### Actual Behaviour

The output of the above commands is:
```text
Error: Failed when running cargo-doc on <...>/ielr/target/semver-checks/local-ielr-0_1_0/Cargo.toml:
error: invalid character `@` in pkgid: `ielr@0.1.0`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
```

### Expected Behaviour

The project is checked without this error

#### Software version

cargo-semver-checks 0.20.0 (e28327b)

#### Operating system

Linux 5.19.0-41-generic

#### Command-line

```bash
/home/arnaud/.cargo/bin/cargo-semver-checks semver-checks --bugreport 
```

#### cargo version

```
> cargo -V 
cargo 1.58.0 (f01b232bc 2022-01-19)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

### Build Configuration

In `.cargo/config.toml`
```toml
[target.'cfg(feature = "cargo-clippy")']
# Catch debugging remnants.
# They cannot be in lib.rs, because of a clippy bug: see <https://github.com/rust-lang/rust-clippy/issues/6610>.
rustflags = [
    "-Wclippy::print_stdout",
    "-Wclippy::print_stderr",
    "-Wclippy::dbg_macro",
]
```

In `rust-toolchain.toml`:
```toml
[toolchain]
channel = "1.58"
components = ["rustfmt", "clippy"]
profile = "minimal"
```
