### ISSUE TITLE
Can't use sparse registry mirror 

### ISSUE THREAD

**Issue by inflation** [obi1kenobi/cargo-semver-checks#487]
### Steps to reproduce the bug with the above code

I'm having this config for the mirror of crates.io:

```toml
[source.crates-io]
replace-with = 'tuna'

[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.tuna]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
```

### Actual Behaviour

`cargo semver-checks check-release` failed with:
```
Error: The repo at path /Users/inflation/.cargo/registry/index/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2 is unusable due to having an invalid HEAD reference: reference 'refs/heads/master' not found; class=Reference (4); code=NotFound (-3)
```

### Expected Behaviour

Checks normally

#### Software version

cargo-semver-checks 0.22.1

#### Operating system

macOS 13.4.1 (Darwin 22.5.0)

#### Command-line

```bash
/Users/inflation/.cargo/bin/cargo-semver-checks semver-checks --bugreport
```

#### cargo version

```
> cargo -V
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
```

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,v8.1a,v8.2a,v8.3a,v8.4a,vh
- Host: aarch64-apple-darwin
