### ISSUE TITLE
Error: no crates with library targets selected, nothing to semver-check

### ISSUE THREAD

**Issue by larrydewey** [obi1kenobi/cargo-semver-checks#660]
### Steps to reproduce the bug with the above code

1. Download the crate (https://github.com/virtee/sev).
2. Install cargo-semver-checks and dependencies.
3. Run cargo-semver-checks.

### Actual Behaviour

```zsh
~/git/sev$ cargo semver-checks check-release --default-features --features openssl
Error: no crates with library targets selected, nothing to semver-check
```

### Expected Behaviour

It should be able to check the semver between the versions.

#### Software version

cargo-semver-checks 0.28.0

#### Operating system

Linux 6.7.0-rc6-next-20231222-snp-host-6b293770d

#### Command-line

```bash
/home/amd/.cargo/bin/cargo-semver-checks semver-checks --bugreport 
```

#### cargo version

```
> cargo -V 
cargo 1.73.0 (9c4383fb5 2023-08-26)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2

### Cargo.toml:
```toml
[package]
name = "sev"
version = "3.0.0"
authors = [
    "Nathaniel McCallum <npmccallum@redhat.com>",
    "The VirTee Project Developers",
]
license = "Apache-2.0"
edition = "2018"
homepage = "https://github.com/virtee/sev"
repository = "https://github.com/virtee/sev"
description = "Library for AMD SEV"
readme = "README.md"
keywords = ["amd", "sev"]
categories = [
    "os",
    "os::linux-apis",
    "parsing",
    "network-programming",
    "hardware-support",
]
exclude = [".gitignore", ".github/*"]
rust-version = "1.70.0"

[badges]
# See https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section
github = { repository = "virtee/sev", workflow = "test" }
#github = { repository = "virtee/sev", workflow = "lint" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "virtee/sev" }
is-it-maintained-open-issues = { repository = "virtee/sev" }

[lib]
crate-type = ["staticlib", "dylib", "rlib"]
name = 'sev'
path = "src/lib.rs"
doc = false

[features]
default = ["sev", "snp"]
hw_tests = []
dangerous_hw_tests = ["hw_tests"]
sev = []
snp = []
crypto_nossl = ["dep:p384", "dep:rsa", "dep:sha2", "dep:x509-cert"]

[target.'cfg(target_os = "linux")'.dependencies]
iocuddle = "0.1"

[dependencies]
openssl = { version = "0.10", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
bitflags = "1.2"
codicon = "3.0"
dirs = "5.0"
serde-big-array = "0.5.1"
static_assertions = "^1.1.0"
bitfield = "^0.13"
uuid = { version = "^1.5", features = ["serde"] }
bincode = "^1.3"
hex = "0.4.3"
libc = "0.2.150"
lazy_static = "1.4.0"
p384 = { version = "0.13.0", optional = true }
rsa = { version = "0.9.2", optional = true }
sha2 = { version = "0.10.8", optional = true }
x509-cert = { version = "0.2.4", optional = true }
byteorder = "1.4.3"

[dev-dependencies]
kvm-ioctls = ">=0.12"
kvm-bindings = ">=0.6"
serial_test = "2.0"
```

### Additional Context

I have attempted to modify the `crate-type` inside of `[lib]`, but in order to generate the C libraries via Meson, these should remain the same. I have found that switching `"rlib"` to `"lib"` will cause the tool to "work," but it still does not seem to recognize the published information, and outputs:

```zsh
~/git/sev$ cargo semver-checks check-release --baseline-rev main --default-features --features openssl
     Cloning main
Error: no crates with library targets selected, nothing to semver-check
```

Is there something I am missing?
